# Generated by Django 6.0.1 on 2026-08-16 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='naziv', max_length=100)),
                ('start_date', models.DateField(db_column='datum_pocetka')),
                ('end_date', models.DateField(db_column='datum_zavrsetka')),
                ('number_of_nights', models.PositiveIntegerField(db_column='broj_nocenja', default=3)),
                ('price', models.DecimalField(db_column='cena', decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField(db_column='broj_mesta')),
                ('description', models.TextField(blank=True, db_column='opis')),
            ],
            options={
                'verbose_name': 'arrangement',
                'verbose_name_plural': 'arrangements',
                'db_table': 'agency_aranzman',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='naziv', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'db_table': 'agency_drzava',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('arrangement', models.ForeignKey(db_column='aranzman_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='agency.arrangement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agency_booking',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='naziv', max_length=100)),
                ('image', models.ImageField(blank=True, db_column='slika', null=True, upload_to='destinacije/')),
                ('country', models.ForeignKey(db_column='drzava_id', on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='agency.country')),
            ],
            options={
                'verbose_name': 'destination',
                'verbose_name_plural': 'destinations',
                'db_table': 'agency_destinacija',
            },
        ),
        migrations.AddField(
            model_name='arrangement',
            name='destination',
            field=models.ForeignKey(db_column='destinacija_id', on_delete=django.db.models.deletion.RESTRICT, related_name='arrangements', to='agency.destination'),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='naziv', max_length=200)),
                ('image', models.ImageField(blank=True, db_column='slika', null=True, upload_to='hoteli/')),
                ('rating', models.DecimalField(db_column='ocena', decimal_places=1, max_digits=2)),
                ('price_per_night', models.DecimalField(db_column='cena_nocenja', decimal_places=2, max_digits=8)),
                ('destination', models.ForeignKey(db_column='destinacija_id', on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='agency.destination')),
            ],
            options={
                'verbose_name': 'hotel',
                'verbose_name_plural': 'hotels',
                'db_table': 'agency_hotel',
            },
        ),
        migrations.AddField(
            model_name='arrangement',
            name='hotel',
            field=models.ForeignKey(db_column='hotel_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrangements', to='agency.hotel'),
        ),
    ]
