# Generated by Django 6.0.1 on 2026-01-20 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aranzman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum_pocetka', models.DateField()),
                ('datum_zavrsetka', models.DateField()),
                ('broj_mesta', models.IntegerField()),
                ('destinacija', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='aranzmani', to='turizam.destinacija')),
            ],
        ),
    ]
