# Generated by Django 6.0.1 on 2026-01-27 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizam', '0002_aranzman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drzava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='destinacija',
            name='drzava',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aranzmani', to='turizam.drzava'),
        ),
    ]
