# Generated by Django 6.0.1 on 2026-01-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizam', '0003_drzava_alter_destinacija_drzava'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinacija',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='destinacije/'),
        ),
    ]
