# Generated by Django 6.0.1 on 2026-01-30 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizam', '0004_destinacija_slika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='hoteli/')),
                ('ocena', models.DecimalField(decimal_places=1, max_digits=2)),
                ('cena_nocenja', models.DecimalField(decimal_places=2, max_digits=8)),
                ('destinacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoteli', to='turizam.destinacija')),
            ],
        ),
    ]
