# Generated by Django 6.0.1 on 2026-01-31 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turizam', '0005_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aranzman',
            name='broj_nocenja',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='aranzman',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aranzmani', to='turizam.hotel'),
        ),
        migrations.AddField(
            model_name='aranzman',
            name='opis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aranzman',
            name='broj_mesta',
            field=models.PositiveIntegerField(),
        ),
    ]
